[package]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
futures = "*"
enum_dispatch = "0.3"
chrono = { version = "0.4.38", features = ["serde", "std"] }
tracing = "*"
tracing-subscriber = "*"
polars = { version = "0.43", features = ["lazy"] }

sqlx = { version = "0.8", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "chrono",
] }

config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

goap = { path = "../lib/goap" }
api = { path = "../lib/api" }
support = { path = "../lib/support" }

[dev-dependencies]
assert-json-diff = "2.0.2"
