[package]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.38", features = ["serde", "std"] }
thiserror = "1"
tracing = "*"
tracing-subscriber = "*"
polars = { version = "0.42.0", features = ["lazy"] }

sqlx = { version = "0.7", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "chrono",
] }

config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }

goap = { path = "../lib/goap" }
api = { path = "../lib/api" }
support = { path = "../lib/support" }

[dev-dependencies]
assert-json-diff = "2.0.2"
