services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Berlin
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    ports:
      - "8090:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"

