-- heating readings are reset to zero at the end of the year
CREATE OR REPLACE VIEW energy_reading_total AS
(
	WITH
		YEARLY_END_VALUES AS (
			SELECT
				TYPE,
				NAME,
				DATE_PART('year', TIMESTAMP) AS YEAR,
				MAX(VALUE) AS YEARLY_MAX_VALUE
			FROM
				ENERGY_READING
			GROUP BY
				YEAR,
				TYPE,
				NAME
		),
		YEAR_OFFSET_VALUES AS (
			SELECT
				TYPE,
				NAME,
				YEAR,
				YEARLY_MAX_VALUE,
				SUM(YEARLY_MAX_VALUE) OVER (
					PARTITION BY
						TYPE,
						NAME
					ORDER BY
						YEAR
				) AS CUMULATIVE_VALUE
			FROM
				YEARLY_END_VALUES
		)
	SELECT
		ENERGY_READING.ID,
		ENERGY_READING.TYPE,
		ENERGY_READING.NAME,
		ENERGY_READING.TIMESTAMP,
		ENERGY_READING.VALUE + COALESCE(YEAR_OFFSET_VALUES.CUMULATIVE_VALUE, 0) AS VALUE
	FROM
		ENERGY_READING
		LEFT OUTER JOIN YEAR_OFFSET_VALUES ON ENERGY_READING.TYPE = YEAR_OFFSET_VALUES.TYPE
		AND ENERGY_READING.NAME = YEAR_OFFSET_VALUES.NAME
		AND DATE_PART('year', ENERGY_READING.TIMESTAMP) - 1 = YEAR_OFFSET_VALUES.YEAR
	WHERE
		ENERGY_READING.TYPE = 'heating'
)
UNION
(
	SELECT
		ID,
		TYPE,
		NAME,
		TIMESTAMP,
		VALUE
	FROM
		ENERGY_READING
	WHERE
		TYPE != 'heating'
)
